name: Build NetHunter Kernel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install bc bison build-essential zstd clang flex g++-multilib libc6-dev-i386 lib32ncurses5-dev lib32z1-dev libelf-dev libssl-dev libxml2-utils lzop python3 rsync unzip -y

      - name: Compile Kernel for N975F
        run: |
          chmod +x cruelbuild
          ./cruelbuild mkimg name="NetHunter-MITM" model=N975F +magisk +nohardening

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetHunter-Kernel-N975F
          path: "*.img"
